### ISSUE TITLE
Error reading SQS queue - Timeout::Error

### ISSUE THREAD

**Issue by cdenneen** [logstash-plugins/logstash-input-sqs#14]
Also the issue I think is not just checksum's but any sort of issue... (plugin doesn't restart as expected just dies)

{:timestamp=>"2015-06-11T16:27:43.449000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"int-LogQueue", :level=>:error}

Logstash 1.4.2:

We've seen this when the queue has like 1M messages the timeout happens.

I have 8 threads on the SQS input and looking through the log you can watch them all die:

```
{:timestamp=>"2015-06-11T12:53:22.236000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"int-LogQueue", :level=>:error}
{:timestamp=>"2015-06-11T13:05:04.023000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"int-LogQueue", :level=>:error}
{:timestamp=>"2015-06-11T13:10:38.453000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"int-LogQueue", :level=>:error}
{:timestamp=>"2015-06-11T13:19:27.005000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"int-LogQueue", :level=>:error}
{:timestamp=>"2015-06-11T13:22:55.558000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"int-LogQueue", :level=>:error}
{:timestamp=>"2015-06-11T13:25:58.123000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"int-LogQueue", :level=>:error}
{:timestamp=>"2015-06-11T13:41:36.046000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"int-LogQueue", :level=>:error}
{:timestamp=>"2015-06-11T13:55:24.643000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"int-LogQueue", :level=>:error}
```

**Comment by cdenneen** [comment]
I'm thinking the thread is timing out trying to list queue that is filled with a lot of items ~1M.
When this happens we've purged the queue and logstash seems to keep up for a few hours and then the threads start dying due to Timeout::Error.
Any restart of the process doesn't fix it because I believe the queue now is too large for the listing to respond, so timeout again and never ingests until purged again.

**Comment by ph** [comment]
In the current implementation of the SQS input, when a non SQS specific error is raised the plugin will just silently stop and never be restarted.

in #18 I have introduced a change in the the error handling that will make the plugin reraise the exception up to the pipeline which will make it restart the `#run` method. This should fix theses kind of issues.

**Comment by cdenneen** [comment]
+1 that's great @ph might you be able to check the s3 input / cloudtrail codec as well for the same logic?

**Comment by ph** [comment]
@cdenneen Will try to check it too, thanks for reminding me.

**Comment by ph** [comment]
#18 released as 1.1.0 implement a new error handling, the errors will bubble up to the pipeline and the pipeline will restart the input.

**Comment by cdenneen** [comment]
@ph looks like the restart is working but still getting errors in log (doesn't seem to be affecting ingestion though anymore since restart is happening)

```
{:timestamp=>"2015-09-02T16:52:11.728000-0400", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::SQS access_key_id=>\"XXXXXX\", secret_access_key=>\"YYYYYY\", queue=>\"logstash-prod-inputqueue\", region=>\"us-east-1\", type=>\"apfeed\", tags=>[\"sqs\"], threads=>8, codec=><LogStash::Codecs::JSON charset=>\"UTF-8\">, debug=>false, polling_frequency=>20>\n  Error: execution expired", :level=>:error}
```

**Comment by ph** [comment]
It shouldn't be affecting the execution, do you get theses often?
Also you should not lose any events since sqs require ack of messages and theses kind of exception make sure we will try to fetch the messages again.

**Comment by cdenneen** [comment]
@ph yes it doesn't seem to be affecting execution but seems to happen very frequently.

**Comment by ph** [comment]
@cdenneen Can you give me details on your OS, JDK?

**Comment by ph** [comment]
Another question, are you running logstash inside the AWS network?

**Comment by cdenneen** [comment]
@ph no reomotely but over direct connect

**Comment by ph** [comment]
I don't think we can improve a lot on that, we are reaching the timeout inside the library. I think the plugins is doing what is expected here: log the exception and restart. I will close this, if this issue is raised a lot we will reopen it.
